#!/usr/bin/env bash
# aur-release.sh — refresh the AUR recipe checksum for the current release.
#
# BACKGROUND
#   The AUR package is published from a SEPARATE git repository that contains
#   only PKGBUILD and .SRCINFO. Those files must point at the published release
#   tarball with a matching sha256sum. The tarball is generated by GitHub from
#   the pushed tag, so the checksum can only be computed AFTER the tag exists.
#
#   This script copies the maintained recipe (dist/arch/PKGBUILD) into the AUR
#   clone, recomputes the checksum against the freshly downloaded tarball, and
#   regenerates .SRCINFO from it. It deliberately stops there: reviewing,
#   committing, and pushing to the AUR remote stay manual.
#
#   makepkg/updpkgsums are Arch-only. On a non-Arch host (the usual dev box)
#   the script runs the exact same tooling inside a throwaway archlinux
#   container; on Arch it runs natively. Either way the result is identical.
#
# USAGE
#   ./dev/aur-release.sh [AUR_REPO_DIR]
#
#   AUR_REPO_DIR   Path to the AUR clone. Defaults to a sibling of the main
#                  repository named "xfce4-meowmenu-plugin-AUR" (i.e. two levels
#                  up from this script's dev/ folder, then into that name).
#
# PREREQUISITE
#   The release tag (vX.Y.Z matching pkgver) must already be pushed to GitHub,
#   otherwise the tarball download 404s and updpkgsums fails.
set -euo pipefail

die() { printf 'aur-release: %s\n' "$*" >&2; exit 1; }

# Resolve every path from the script's own location so the tool works from any
# working directory.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DIST_ARCH="${REPO_ROOT}/dist/arch"

# Default AUR clone: beside the main repo (two levels up from dev/).
AUR_REPO="${1:-$(cd "${REPO_ROOT}/.." && pwd)/xfce4-meowmenu-plugin-AUR}"

[ -f "${DIST_ARCH}/PKGBUILD" ] || die "missing recipe: ${DIST_ARCH}/PKGBUILD"
[ -d "${AUR_REPO}" ]          || die "AUR repo not found: ${AUR_REPO}"
[ -d "${AUR_REPO}/.git" ]     || die "not a git repo: ${AUR_REPO}"

# Read pkgver from the maintained recipe purely for the operator-facing notice;
# updpkgsums itself derives the download URL from the copied PKGBUILD.
PKGVER="$(sed -n 's/^pkgver=//p' "${DIST_ARCH}/PKGBUILD" | head -n1)"
OLD_SUM="$(sed -n "s/^sha256sums=('\\([0-9a-f]*\\)').*/\\1/p" "${AUR_REPO}/PKGBUILD" 2>/dev/null || true)"

printf '==> Releasing AUR recipe for pkgver=%s\n' "${PKGVER:-?}"
printf '    main recipe : %s/PKGBUILD\n' "${DIST_ARCH}"
printf '    AUR clone   : %s\n' "${AUR_REPO}"
printf '    NOTE: tag v%s must already be pushed to GitHub.\n\n' "${PKGVER:-X.Y.Z}"

# 1. Copy the maintained recipe into the AUR clone (single source of truth).
cp "${DIST_ARCH}/PKGBUILD" "${AUR_REPO}/PKGBUILD"

# 2. Remove makepkg leftovers BEFORE recomputing. If a previously downloaded
#    tarball is still present, makepkg/updpkgsums hash that stale local copy
#    instead of re-fetching the published one — the exact trap this tool exists
#    to avoid. Only build outputs are touched; PKGBUILD/.SRCINFO are kept.
rm -rf "${AUR_REPO}/src" "${AUR_REPO}/pkg"
rm -f  "${AUR_REPO}"/*.tar.gz "${AUR_REPO}"/*.pkg.tar.* 2>/dev/null || true

# 3. The actual work: refresh checksum, regenerate metadata, verify download.
#    'updpkgsums'              -> rewrites sha256sums=() against the live tarball
#    'makepkg --printsrcinfo'  -> regenerates .SRCINFO (never hand-edited)
#    'makepkg --verifysource'  -> re-downloads and confirms the new checksum
REFRESH='updpkgsums && makepkg --printsrcinfo > .SRCINFO && makepkg --verifysource'

if command -v updpkgsums >/dev/null 2>&1 && command -v makepkg >/dev/null 2>&1; then
	# Native Arch host. makepkg refuses to run as root; assume a normal user.
	[ "$(id -u)" -ne 0 ] || die "run as a normal user, not root (makepkg refuses root)"
	( cd "${AUR_REPO}" && eval "${REFRESH}" )
else
	# Non-Arch host: run the identical tooling in a disposable container.
	command -v docker >/dev/null 2>&1 \
		|| die "need 'makepkg'+'updpkgsums' (Arch) or 'docker' (any host)"
	printf '==> No native makepkg; using archlinux container.\n\n'
	# Create a build user whose UID matches the host so files written back into
	# the mounted clone (.SRCINFO, downloaded sources) stay owned by the caller.
	# REFRESH is passed via the environment so the container shell expands it;
	# this avoids brittle nested host-side quoting.
	docker run --rm -e HOST_UID="$(id -u)" -e REFRESH="${REFRESH}" \
		-v "${AUR_REPO}:/work" archlinux:base-devel bash -c '
			set -e
			pacman -Sy --noconfirm --needed pacman-contrib >/dev/null
			if getent passwd "$HOST_UID" >/dev/null; then
				u="$(getent passwd "$HOST_UID" | cut -d: -f1)"
			else
				useradd -m -u "$HOST_UID" builder; u=builder
			fi
			chown -R "$HOST_UID" /work
			su "$u" -c "cd /work && $REFRESH"
		'
fi

# 4. Clean the build artifacts the verify step pulled in, so the operator's
#    `git status` shows only the two files that belong on the AUR.
rm -rf "${AUR_REPO}/src" "${AUR_REPO}/pkg"
rm -f  "${AUR_REPO}"/*.tar.gz "${AUR_REPO}"/*.pkg.tar.* 2>/dev/null || true

NEW_SUM="$(sed -n "s/^sha256sums=('\\([0-9a-f]*\\)').*/\\1/p" "${AUR_REPO}/PKGBUILD" | head -n1)"

printf '\n==> Checksum refreshed\n'
printf '    old: %s\n' "${OLD_SUM:-<none>}"
printf '    new: %s\n' "${NEW_SUM:-<unknown>}"
printf '\n==> Pending changes in the AUR clone (review before committing):\n'
git -C "${AUR_REPO}" status --short
printf '\nNext (manual): cd %s && git add PKGBUILD .SRCINFO && git commit && git push\n' "${AUR_REPO}"
